## Universal functions ufunc

In [2]:
import numpy as np

In [3]:
degree=np.array([0,20,45,60,90])
print(degree)


[ 0 20 45 60 90]


In [4]:
#convert degree to radian
radian=np.deg2rad(degree)
print(radian)

[0.         0.34906585 0.78539816 1.04719755 1.57079633]


### sin,inverse sin,hyberbolic,inverse hyperbolic,hypot,ceil,floor,exp,square,rint,isna,isfinite,log,log10,log2,log1p,

In [5]:
#sin
print('Sine of angles in the array:') 
sine_value = np.sin(radian) 
print(sine_value)


Sine of angles in the array:
[0.         0.34202014 0.70710678 0.8660254  1.        ]


In [6]:
#cos
print('cos of angles in the array:') 
cos_value = np.cos(radian) 
print(cos_value)

cos of angles in the array:
[1.00000000e+00 9.39692621e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


In [7]:
#tan
print('tan of angles in the array:') 
tan_value = np.tan(radian) 
print(tan_value)

tan of angles in the array:
[0.00000000e+00 3.63970234e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [8]:
# inverse sine of sine values 
print('Inverse Sine of sine values:') 
print(np.rad2deg(np.arcsin(sine_value))) 

Inverse Sine of sine values:
[ 0. 20. 45. 60. 90.]


In [8]:
print('cose of angles in the array:') 
cos_value = np.arccos(cos_value) 
print(cos_value)

cose of angles in the array:
[0.         0.34906585 0.78539816 1.04719755 1.57079633]


In [9]:
print('tan of angles in the array:') 
tan_value = np.arctan(tan_value) 
print(tan_value)

tan of angles in the array:
[0.         0.34906585 0.78539816 1.04719755 1.57079633]


In [10]:
# hyperbolic sine of angles 
print('Sine hyperbolic of angles in the array:') 
sineh_value = np.sinh(radian) 
print(np.sinh(radian)) 

Sine hyperbolic of angles in the array:
[0.         0.35619793 0.86867096 1.24936705 2.3012989 ]


In [32]:
print('cose hyperbolic of angles in the array:') 
coseh_value = np.cosh(radian) 
print(np.cosh(radian)) 


cose hyperbolic of angles in the array:
[1.         1.06154461 1.32460909 1.60028686 2.50917848]


In [33]:
print('tanhyperbolic of angles in the array:') 
tanh_value = np.tanh(radian) 
print(np.tanh(radian)) 

tanhyperbolic of angles in the array:
[0.         0.33554683 0.6557942  0.78071444 0.91715234]


In [34]:
# inverse sine hyperbolic  
print('Inverse Sine hyperbolic:') 
print(np.sin(sineh_value)) 

Inverse Sine hyperbolic:
[0.         0.34871335 0.76347126 0.94878485 0.74483916]


In [35]:
print('Inverse cose hyperbolic:') 
print(np.cos(coseh_value)) 

Inverse cose hyperbolic:
[ 0.54030231  0.48752405  0.24370794 -0.02948626 -0.80660286]


In [36]:
print('Inverse tan hyperbolic:') 
print(np.cos(tanh_value)) 

Inverse tan hyperbolic:
[1.         0.94423039 0.79256388 0.71041091 0.6080833 ]


In [14]:
# hypot function demonstration 
base = 4
height = 3
print('hypotenuse of right triangle is:') 
print(np.hypot(base, height)) 

hypotenuse of right triangle is:
5.0


In [9]:
#abs
b=np.array([-81.9,100.6,4,64])
print(np.abs(b))

[ 81.9 100.6   4.   64. ]


In [10]:
#square
b=np.array([81,100,4,64])
print(np.sqrt(b))

[ 9. 10.  2.  8.]


In [11]:
#exp
b=np.array([81,100,4,64])
print(np.exp(b))

[1.50609731e+35 2.68811714e+43 5.45981500e+01 6.23514908e+27]


In [12]:
#ceil 
b=np.array([81.8,100.2,4.8,64])
print(np.ceil(b))

[ 82. 101.   5.  64.]


In [13]:
#floor 
b=np.array([81.4,100.2,4.9,64])
print(np.floor(b))

[ 81. 100.   4.  64.]


In [15]:
#rint
b=np.array([80.8,100,8.6,64.4])
print(np.rint(b))

[ 81. 100.   9.  64.]


In [18]:
#isnan
b=np.array([81,8,4,64])
print(np.isnan(b))

[False False False False]


In [19]:
#isfinite 
b=np.array([81,100,4,64])
print(np.isfinite(b))

[ True  True  True  True]


In [20]:
#ismodf
a=np.array([23.4,34.2,67.2,12.4,78.3])
print(np.modf(a))

(array([0.4, 0.2, 0.2, 0.4, 0.3]), array([23., 34., 67., 12., 78.]))


In [21]:
#log,log10,log2,log1p,
#abs
a=np.array([23.4,34.2,67.2,12.4,78.3])
print(np.log(a))

[3.15273602 3.53222564 4.20767325 2.51769647 4.3605476 ]


In [22]:
a=np.array([23.4,34.2,67.2,12.4,78.3])
print(np.log1p(a))

[3.19458313 3.56104608 4.22244456 2.59525471 4.37323813]


In [23]:
a=np.array([23.4,34.2,67.2,12.4,78.3])
print(np.log10(a))

[1.36921586 1.53402611 1.82736927 1.09342169 1.89376176]


In [24]:
a=np.array([23.4,34.2,67.2,12.4,78.3])
print(np.log2(a))

[4.54843662 5.09592442 6.07038933 3.63226822 6.2909404 ]


### Statistical functions

In [25]:
#max and min weight
weight=np.array([45,78,56,34,57,79,22])
print(np.min(weight))
print(np.max(weight))

22
79


In [26]:
# range of weight i.e. max weight-min weight 
print('Range of the weight of the students: ') 
print(np.ptp(weight)) 

Range of the weight of the students: 
57


In [29]:
# percentile 
print('Weight below which 70 % student fall: ') 
print(np.percentile(weight, 70)) 

Weight below which 70 % student fall: 
61.19999999999998


In [30]:
# mean  
print('Mean weight of the students: ') 
print(np.mean(weight)) 
  
# median  
print('Median weight of the students: ') 
print(np.median(weight))

Mean weight of the students: 
53.0
Median weight of the students: 
56.0


In [31]:
# standard deviation  
print('Standard deviation of weight of the students: ') 
print(np.std(weight)) 
  
# variance  
print('Variance of weight of the students: ') 
print(np.var(weight)) 
  

Standard deviation of weight of the students: 
19.683205313885527
Variance of weight of the students: 
387.42857142857144


In [32]:
# average  
print('Average weight of the students: ') 
print(np.average(weight)) 

Average weight of the students: 
53.0


In [33]:
# construct an array of even and odd numbers 
even = np.array([0, 2, 4, 6, 8, 16, 32]) 
odd = np.array([1, 3, 5, 7, 9, 17, 33]) 
  
# bitwise_and 
print('bitwise_and of two arrays: ') 
print(np.bitwise_and(even, odd)) 
  

bitwise_and of two arrays: 
[ 0  2  4  6  8 16 32]


In [34]:
print('bitwise_or of two arrays: ') 
print(np.bitwise_or(even, odd)) 

bitwise_or of two arrays: 
[ 1  3  5  7  9 17 33]


In [35]:
# bitwise_xor 
print('bitwise_xor of two arrays: ') 
print(np.bitwise_xor(even, odd)) 
   
# invert or not 
print('inversion of even no. array: ') 
print(np.invert(even)) 
  
# left_shift  
print('left_shift of even no. array: ') 
print(np.left_shift(even, 1)) 
  
# right_shift  
print('right_shift of even no. array: ') 
print(np.right_shift(even, 1)) 


bitwise_xor of two arrays: 
[1 1 1 1 1 1 1]
inversion of even no. array: 
[ -1  -3  -5  -7  -9 -17 -33]
left_shift of even no. array: 
[ 0  4  8 12 16 32 64]
right_shift of even no. array: 
[ 0  1  2  3  4  8 16]


### Boolean

In [36]:
bools=np.array([False,False,True,False])
bools.any() #or

True

In [37]:
bools.all() #and

False

In [38]:
bools=np.array([True,True,True,True])
bools.any() #or

True

### Sorting

In [39]:
arr=np.array([-1,-1.56,0,5.98,8.26])
arr

array([-1.  , -1.56,  0.  ,  5.98,  8.26])

In [40]:
arr.sort()
arr

array([-1.56, -1.  ,  0.  ,  5.98,  8.26])

### unique and other set logic

In [41]:
names=np.array(['selvan','Hari','charles','Hari','charles','surya'])
np.unique(names)

array(['Hari', 'charles', 'selvan', 'surya'], dtype='<U7')

In [42]:
sorted(set(names))

['Hari', 'charles', 'selvan', 'surya']

In [43]:
ints=np.array([3,3,3,2,2,1,1,4,4])
np.unique(ints)

array([1, 2, 3, 4])

In [44]:
values=np.array([6,0,0,3,2,5,6])
np.in1d(values,[2,3,6])

array([ True, False, False,  True,  True, False,  True])

### Array set operations

unique(x)
intersect1d(x,y)
union1d(x,y)
in1d(x,y)
setdiff1d(x,y)
setxor1d(x,y)

In [45]:
#intersect1d(x,y)
np.intersect1d([1, 3, 4, 3], [3, 1, 2, 1])


array([1, 3])

In [46]:
#To intersect more than two arrays, use functools.reduce:
from functools import reduce
reduce(np.intersect1d, ([1, 3, 4, 3], [3, 1, 2, 1], [6, 3, 4, 2]))

array([3])

In [42]:
#isin
element=2*np.arange(4).reshape(2,2)
element

array([[0, 2],
       [4, 6]])

In [43]:
test_element=[1,2,4,8]

In [44]:
mask=np.isin(element,test_element)
mask

array([[False,  True],
       [ True, False]])

In [45]:
element[mask]

array([2, 4])

In [46]:
mask=np.isin(element,test_element,invert=True)
mask

array([[ True, False],
       [False,  True]])

In [47]:
element[mask]

array([0, 6])

In [49]:
#setdiff1d
a = np.array([1, 2, 3, 2, 4, 1,8])
b = np.array([3, 4, 5, 6])
np.setdiff1d(a,b)

array([1, 2, 8])

In [52]:
#setxor1d
a = np.array([1, 2, 3, 2, 4])
b = np.array([2, 3, 5, 7, 5,9])
np.setxor1d(a,b)

array([1, 4, 5, 7, 9])

In [53]:
#union1d
np.union1d([-1, 0, 1], [-2, 0, 2])


array([-2, -1,  0,  1,  2])

In [54]:
#To find the union of more than two arrays, use functools.reduce:
from functools import reduce

In [55]:
reduce(np.union1d, ([1, 3, 4, 3,8], [3, 1, 2, 1], [6, 3, 4, 2]))

array([1, 2, 3, 4, 6, 8])