# Numpy ndarray
    1.A multidimensional array object
    2.Create ndarray
    3.Array create function:
            1.ones and zeros
            2.Existing array
     4.Operation betweem array and scalar(vectorization)

In [1]:
import numpy as np

### 1.A Multidimensional Array Object

One of the key features of NumPy is its N-dimensional array object, or ndarray, which
is a fast, flexible container for large data sets in Python. Arrays enable you to perform
mathematical operations on whole blocks of data using similar syntax to the equivalentoperations between scalar elements:

In [2]:
data=np.array([1,2,4,5])
data

array([1, 2, 4, 5])

In [3]:
data*10

array([10, 20, 40, 50])

In [4]:
data+data

array([ 2,  4,  8, 10])

In [5]:
data.shape

(4,)

In [6]:
data.dtype

dtype('int32')

### 2.Creating ndarrays
            Create
            shape
            datatype
            ones empty and zeros fill
            arange

In [7]:
#import library
import numpy as np

The easiest way to create an array is to use the array function.
This accepts any sequence-like object (including other arrays) and produces 
a new NumPy array containing the passed data. For example, a list is a good candidate for conversion:


In [8]:
data=[5.6,7,8,9.0]
arr=np.array(data)
arr

array([5.6, 7. , 8. , 9. ])

In [9]:
arr1=np.array([5.6,7,8,9.0])
arr1

array([5.6, 7. , 8. , 9. ])

Nested sequences, like a list of equal-length lists, will be converted into a multidimensional array:

In [10]:
data1=[[4,5,6,7],[9,0,7,8]]
arr2=np.array(data1)
arr2

array([[4, 5, 6, 7],
       [9, 0, 7, 8]])

In [26]:
ar=np.array([[5.6,7,8,9.0,7],[8.0,9.0,7,8,0],[4,5,7,9,8],[8,9,0,4,6]])
ar


array([[5.6, 7. , 8. , 9. , 7. ],
       [8. , 9. , 7. , 8. , 0. ],
       [4. , 5. , 7. , 9. , 8. ],
       [8. , 9. , 0. , 4. , 6. ]])

In [27]:
ar.ndim

2

show the dimensions shape

In [28]:
arr2.ndim


2

In [29]:
arr1.ndim

1

In [30]:
arr2.shape

(2, 4)

In [31]:
arr1.shape

(4,)

In [32]:
ar.shape

(4, 5)

datatype

In [33]:
arr1.dtype

dtype('float64')

In [34]:
arr2.dtype

dtype('int32')

In [35]:
ar.dtype

dtype('float64')

Data Types for ndarrays

In [40]:
a=np.array([[12,45,67],[8,9,0]],dtype='double')
a.dtype

dtype('float64')

In [41]:
a

array([[12., 45., 67.],
       [ 8.,  9.,  0.]])

In [42]:
b=np.arange(7)
b

array([0, 1, 2, 3, 4, 5, 6])

In [43]:
c=np.array([4.5,6.7,8.9])

You can also use another array’s dtype attribute:


In [44]:
c.astype(b.dtype)

array([4, 6, 8])

 Ones and zeros

In addition to np.array, there are a number of other functions for creating new arrays.
As examples, zeros and ones create arrays of 0’s or 1’s, respectively, with a given length
or shape. empty creates an array without initializing its values to any particular value.
To create a higher dimensional array with these methods, pass a tuple for the shape:

In [40]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [42]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [50]:
np.zeros((3,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

It’s not safe to assume that np.empty will return an array of all zeros. In
many cases, as previously shown, it will return uninitialized garbage
values.


In [79]:
np.empty((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

arange

arange is an array-valued version of the built-in Python range function:

In [52]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

numpy.empty(shape, dtype=float, order='C')
Return a new array of given shape and type, without initializing entries.

## Array Create Function
1.Ones and Zeros

2.From Existing data


In [56]:
np.empty((2,3),dtype='int',order='C')

array([[ 543236207, 1953720684,  543584032],
       [1953265005, 1701605481, 1651864352]])

numpy.empty_like

numpy.empty_like(prototype, dtype=None, order='K', subok=True, shape=None)
Return a new array with the same shape and type as a given array.

In [57]:
ar

array([[5.6, 7. , 8. , 9. , 7. ],
       [8. , 9. , 7. , 8. , 0. ],
       [4. , 5. , 7. , 9. , 8. ],
       [8. , 9. , 0. , 4. , 6. ]])

In [58]:
np.empty_like(ar)

array([[5.6, 7. , 8. , 9. , 7. ],
       [8. , 9. , 7. , 8. , 0. ],
       [4. , 5. , 7. , 9. , 8. ],
       [8. , 9. , 0. , 4. , 6. ]])

numpy.eye

numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')[source]
Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [61]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [46]:
np.eye(5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

numpy.identity

numpy.identity(n, dtype=None)
Return the identity array.

The identity array is a square array with ones on the main diagonal.

In [63]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

numpy.ones

np.ones(shape, dtype=None, order='C')
Return a new array of given shape and type, filled with ones.



In [64]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [65]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [66]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [67]:
np.ones((3,2,3),dtype='float')

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

numpy.ones_like

numpy.ones_like(a, dtype=None, order='K', subok=True, shape=None)[source]
Return an array of ones with the same shape and type as a given array.

In [68]:
y=np.arange(6,dtype='float')
y

array([0., 1., 2., 3., 4., 5.])

In [69]:
np.ones_like(y)

array([1., 1., 1., 1., 1., 1.])

In [70]:
np.ones_like(y,dtype=int)

array([1, 1, 1, 1, 1, 1])

numpy.zeros

numpy.zeros(shape, dtype=float, order='C')
Return a new array of given shape and type, filled with zeros.

In [71]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [77]:
np.zeros((2,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [75]:
np.zeros((2,3,3),dtype='float')

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [80]:
np.zeros(2,)

array([0., 0.])

numpy.zeros_like

numpy.zeros_like(a, dtype=None, order='K', subok=True, shape=None)
Return an array of zeros with the same shape and type as a given array.

In [81]:
x=np.arange(3)
x

array([0, 1, 2])

In [82]:
np.zeros_like(x)

array([0, 0, 0])

In [83]:
x=np.arange(6)
x=x.reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [84]:
np.zeros_like(x)

array([[0, 0, 0],
       [0, 0, 0]])

numpy.zeros_like

numpy.zeros_like(a, dtype=None, order='K', subok=True, shape=None)
Return an array of zeros with the same shape and type as a given array.

In [76]:
np.full((2,2),np.inf)

array([[inf, inf],
       [inf, inf]])

In [77]:
np.full((2,2),100)

array([[100, 100],
       [100, 100]])

numpy.full_like

numpy.full_like(a, fill_value, dtype=None, order='K', subok=True, shape=None
Return a full array with the same shape and type as a given array.

In [85]:
x=np.arange(6,dtype=int)
x

array([0, 1, 2, 3, 4, 5])

In [88]:
np.full_like(x,1.1)

array([1, 1, 1, 1, 1, 1])

In [89]:
np.full_like(x,0.4,dtype='float')

array([0.4, 0.4, 0.4, 0.4, 0.4, 0.4])

In [90]:
np.full_like(x,5,dtype='double')

array([5., 5., 5., 5., 5., 5.])

## From existing data

numpy.array

numpy.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
Create an array.

In [91]:
np.array([2,3,4])

array([2, 3, 4])

In [92]:
#Upcasting
np.array([2,3,4.5])

array([2. , 3. , 4.5])

In [96]:
#more than one dimensions
a=np.array([[2,3,4],[6,7,8]])
a

array([[2, 3, 4],
       [6, 7, 8]])

In [97]:
a.ndim

2

In [94]:
#minimum 2 dimensions
np.array([2,3,4], ndmin=2)


array([[2, 3, 4]])

In [62]:
#Type provided:
np.array([2,3,4],dtype=complex)

array([2.+0.j, 3.+0.j, 4.+0.j])

In [63]:
#Data-type consisting of more than one element:
a=np.array([(1,2),(3,4)],dtype=[('x' ,'>i4'),('y','>i4')])
print(a['x'])
print(a['y'])

[1 3]
[2 4]


In [117]:
#Creating an array from sub-classes:
np.array(np.mat('1,2;3,4'))

array([[1, 2],
       [3, 4]])

In [101]:
np.array(np.mat('1,2,4;3,4,5'),subok=True)

matrix([[1, 2, 4],
        [3, 4, 5]])

numpy.asarray

(a, dtype=None, order=None)
Convert the input to an array.

In [105]:
#Convert a list into an array:
a=[1,2,3]
np.asarray(a)

array([1, 2, 3])

In [106]:
#Existing arrays are not copied:
a=np.array([1,2])
np.asarray(a)is a

True

In [108]:
#If dtype is set, array is copied only if dtype does not match:
np.asarray(a,dtype='float32')
np.asarray(a,dtype='float64')is a

False

numpy.asarray

numpy.asarray(a, dtype=None, order=None)
Convert the input to an array.

In [109]:
issubclass(np.recarray,np.ndarray)

True

In [130]:
a=np.array([[1,2,3],[4,5,6]],dtype=float).view(np.recarray)
a

rec.array([[1., 2., 3.],
           [4., 5., 6.]],
          dtype=float64)

In [131]:
np.asarray(a) is a

False

In [132]:
np.asanyarray(a) is a

True

numpy.asanyarray

numpy.asanyarray(a, dtype=None, order=None)[source]
Convert the input to an ndarray, but pass ndarray subclasses through.

In [112]:
a=[1,2]
np.asanyarray(a)

array([1, 2])

Instances of ndarray subclasses are passed through as-is:



In [145]:
a=np.array([(1,2.0),(3.0,4)],dtype='float').view(np.recarray)
np.asanyarray(a) is a

True

numpy.ascontiguousarray

numpy.ascontiguousarray(a, dtype=None)
Return a contiguous array (ndim >= 1) in memory (C order).

In [126]:
x=np.arange(6).reshape(2,3)

np.ascontiguousarray(x,dtype='float32')

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)

In [127]:
x.ndim

2

In [129]:
x.flags['C_CONTIGUOUS']

True

numpy.asmatrix

numpy.asmatrix(data, dtype=None)[source]
Interpret the input as a matrix.

Unlike matrix, asmatrix does not make a copy if the input is already a matrix or an ndarray. 
Equivalent to matrix(data, copy=False).

In [115]:
x=np.array([[2,3],[4,6]])
x

array([[2, 3],
       [4, 6]])

In [117]:
m=np.asmatrix(x)

In [118]:
x[0,0]=5

In [119]:
x

array([[5, 3],
       [4, 6]])

In [120]:
m

matrix([[5, 3],
        [4, 6]])

In [121]:
x=np.array([[1,3],[4,6]])
x

array([[1, 3],
       [4, 6]])

In [122]:
n=np.matrix(x)


In [123]:
x[0,0]=6

In [124]:
x

array([[6, 3],
       [4, 6]])

In [125]:
n

matrix([[1, 3],
        [4, 6]])

numpy.copy

numpy.copy(a, order='K')
Return an array copy of the given object.

In [140]:
#Create an array x, with a reference y and a copy z:
x=np.array([1,2])
y=x
z=np.copy(x)

In [141]:
z

array([1, 2])

In [143]:
y

array([1, 2])

In [144]:
#Note that, when we modify x, y changes, but not z:
x[0]=4
x[0]==y[0]

True

In [145]:
z[0] is x[0]

False

In [146]:
y[0] is z[0]

False

numpy.frombuffer

numpy.frombuffer(buffer, dtype=float, count=-1, offset=0)
Interpret a buffer as a 1-dimensional array.

If the buffer has data that is not in machine byte-order, this should be specified as part of the data-type, e.g.:

In [184]:
dt = dt.newbyteorder('>')
dt

dtype('>i4')

In [198]:
s=b'hello python'
np.frombuffer(s,dtype='S1',count=6,offset=6)

array([b'p', b'y', b't', b'h', b'o', b'n'], dtype='|S1')

In [205]:
np.frombuffer(b'\x01\x02\x03\x04\x05', dtype=np.uint8, count=5)

array([1, 2, 3, 4, 5], dtype=uint8)

In [207]:
np.frombuffer(b'\x01\x02', dtype=np.uint8)

array([1, 2], dtype=uint8)

## Operations between Arrays and Scalars


Arrays are important because they enable you to express batch operations on data
without writing any for loops. 

This is usually called VECTORIZATION 

Any arithmetic operations between equal-size arrays applies the operation elementwise:


In [147]:
arr=np.array([[2,4,6],[4,5,8],[3,4,5]])
arr

array([[2, 4, 6],
       [4, 5, 8],
       [3, 4, 5]])

In [148]:
arr*2

array([[ 4,  8, 12],
       [ 8, 10, 16],
       [ 6,  8, 10]])

In [149]:
arr+2

array([[ 4,  6,  8],
       [ 6,  7, 10],
       [ 5,  6,  7]])

In [150]:
arr-2

array([[0, 2, 4],
       [2, 3, 6],
       [1, 2, 3]])

In [151]:
arr/2

array([[1. , 2. , 3. ],
       [2. , 2.5, 4. ],
       [1.5, 2. , 2.5]])

In [152]:
arr*arr

array([[ 4, 16, 36],
       [16, 25, 64],
       [ 9, 16, 25]])

https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html#from-existing-data