# Indexing
    1.Indexing and slicing in array
    2.Advance indexing
        *Integer indexing
        *Boolean Indexing
    3.Fancy Indexing
    4.Transposing arrays
    5.swapping axes in transpose

In [1]:
import numpy as np

### Indexing and slicing

### 1-D array indexing

In [2]:
li=np.arange(10)
li

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
li[0]

0

In [4]:
li[-1]

9

In [5]:
li[5]

5

### 2-D array indexing

In [7]:
l2=np.array([[1,2,4],[5,6,7]])
l2

array([[1, 2, 4],
       [5, 6, 7]])

In [10]:
l2[0][1]

2

In [11]:
l2[1]

array([5, 6, 7])

In [12]:
l2[0][2]

4

In [13]:
l2[1][1]

6

### Slicing

In [14]:
li

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
li[3:8]

array([3, 4, 5, 6, 7])

In [16]:
li[5:]

array([5, 6, 7, 8, 9])

In [17]:
li[2:8:2]

array([2, 4, 6])

In [18]:
li[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
li[:4]

array([0, 1, 2, 3])

In [20]:
s=slice(2,8,2)
li[s]

array([2, 4, 6])

### Advance indexing
1.Integer indexing
2.Boolean indexing

### Integer indexing

In [21]:
x=np.array([[1,2],[3,4],[5,6],[7,9]])
x

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 9]])

In [22]:
x[1:3]

array([[3, 4],
       [5, 6]])

In [23]:
x[0:4,0:1]

array([[1],
       [3],
       [5],
       [7]])

In [24]:
x[0:4,1:2]

array([[2],
       [4],
       [6],
       [9]])

In [30]:
x

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 9]])

In [62]:
#corner value only

rows=np.array([[0,0],[0,1]])
cols=np.array([[0,1],[0,1]])

y=x[rows,cols]
y


array([[0, 1],
       [0, 5]])

### Boolean indexing

In [34]:
x

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 9]])

In [35]:
x[x>5]

array([6, 7, 9])

In [36]:
x[x<5]

array([1, 2, 3, 4])

In [37]:
x[x==5]

array([5])

In [39]:
x[x==11]

array([], dtype=int32)

### Fancy Indexing

In [35]:
rand=np.random.RandomState(29)
x=rand.randint(10,size=10)
print(x)


[5 3 2 8 0 9 1 8 5 3]


In [36]:
print(x[3],x[4],x[-1])

8 0 3


In [38]:
#Alternatively, we can pass a single list or array of indices to obtain the same result:
ind=[3,4,-1]
x[ind]

array([8, 0, 3])

In [39]:
#When using fancy indexing, the shape of the result reflects the shape of the index 
#arrays rather than the shape of the array being indexed:
ind=np.array([[3,4],[3,5]])
x[ind]

array([[8, 0],
       [8, 9]])

In [40]:
#fancy indexing also works in multiple dimensions. Consider the following array:
x=np.arange(12).reshape((3,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
#Like with standard indexing, the first index refers to the row, and the second to the column:
row=np.array([0,1,2])
col=np.array([1,2,1])
x[row,col]

array([1, 6, 9])

In [42]:
x[row[:, np.newaxis],col]

array([[ 1,  2,  1],
       [ 5,  6,  5],
       [ 9, 10,  9]])

In [43]:
#fancy indexing can be combined with other indexing schemes
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [44]:
x[2,[2,0,1]]


array([10,  8,  9])

In [45]:
x[1:,[2,0,1]]

array([[ 6,  4,  5],
       [10,  8,  9]])

In [46]:
#masking
mask = np.array([0,1,0,1], dtype=bool)
x[row[:, np.newaxis], mask]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [84]:
#Modifying Values with Fancy Indexing
y=np.arange(10)
i=np.array([2,3,4,8])
y[i]=24
y

array([ 0,  1, 24, 24, 24,  5,  6,  7, 24,  9])

In [85]:
y[i]-=10
y

array([ 0,  1, 14, 14, 14,  5,  6,  7, 14,  9])

In [86]:
y=np.zeros(10)
y[[0]]=[7]
y

array([7., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [87]:
y[i]+=1
y

array([7., 0., 1., 1., 1., 0., 0., 0., 1., 0.])

myreferences:https://jakevdp.github.io/PythonDataScienceHandbook/02.07-fancy-indexing.html

### Transponsing arrays

In [100]:
matrix=np.array([[1,2,3],[4,5,6]])
print(matrix)
print("\n")
transp=np.transpose(matrix)
print(transp)

[[1 2 3]
 [4 5 6]]


[[1 4]
 [2 5]
 [3 6]]


In [60]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9],[0,2,4]])
print(matrix)
    

t_matrix=zip(*matrix)
for row in t_matrix:
    print(row)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 2 4]]
(1, 4, 7, 0)
(2, 5, 8, 2)
(3, 6, 9, 4)


### Swapping axes in transpose

In [61]:
arr=np.arange(10).reshape((5,2))
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [62]:
arr.T

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [63]:
arr.transpose()

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [47]:
arr=np.arange(24).reshape((2,3,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [48]:
arr.shape

(2, 3, 4)

In [49]:
arr[:, :, 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [54]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [58]:
new_arr = arr.transpose(1, 0, 2)
new_arr

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [59]:
new_arr = arr.transpose(2, 0, 1)
new_arr

array([[[ 0,  4,  8],
        [12, 16, 20]],

       [[ 1,  5,  9],
        [13, 17, 21]],

       [[ 2,  6, 10],
        [14, 18, 22]],

       [[ 3,  7, 11],
        [15, 19, 23]]])

In [60]:
new_arr.shape

(4, 2, 3)

In [104]:
new_arr[0, :, 1]

array([ 4, 16])

In [105]:
new_arr[1, :, 1]

array([ 5, 17])

In [147]:
new_arr[2, :, 1]

array([ 6, 18])

In [148]:
new_arr[3, :, 1]

array([ 7, 19])

In [149]:
new_arr[:, :, 1]

array([[ 4, 16],
       [ 5, 17],
       [ 6, 18],
       [ 7, 19]])

In [61]:
new_arr[:,:,2]

array([[ 8, 20],
       [ 9, 21],
       [10, 22],
       [11, 23]])