In [2]:
import numpy as np

File Input and Output with Arrays

NumPy is able to save and load data to and from disk either in text or binary format


### Storing Arrays on Disk in Binary Format

np.save and np.load are the two workhorse functions for efficiently saving and loading
array data on disk. 

Arrays are saved by default in an uncompressed raw binary format
with file extension .npy.

In [3]:
arr=np.arange(10)
np.save('some_array',arr)

In [4]:
arr1=np.arange(5)

If the file path does not already end in .npy, the extension will be appended. The array
on disk can then be loaded using np.load:


In [5]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

You save multiple arrays in a zip archive using np.savez and passing the arrays as keyword arguments:

In [6]:
np.savez('array_archive.npz', a=arr1, b=arr)

When loading an .npz file, you get back a dict-like object which loads the individual
arrays lazily:

In [7]:
arch=np.load('array_archive.npz')

In [8]:
arch['a']

array([0, 1, 2, 3, 4])

In [9]:
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Linear Algebra

Linear algebra, like matrix multiplication, decompositions, determinants, and other
square matrix math, is an important part of any array library. Unlike some languages
like MATLAB, multiplying two two-dimensional arrays with * is an element-wise
product instead of a matrix dot product. As such, there is a function dot, both an array
method, and a function in the numpy namespace, for matrix multiplication:

In [30]:
x=np.array([[1.,2.,3.],[4.,5.,6.]])
y=np.array([[2.,4.],[5.,7.],[8.,9.]])

In [31]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [32]:
y

array([[2., 4.],
       [5., 7.],
       [8., 9.]])

In [33]:
x.dot(y)

array([[ 36.,  45.],
       [ 81., 105.]])

In [34]:
np.dot(x,np.ones(3
                ))

array([ 6., 15.])

In [14]:
a = np.random.randn(5,5)

In [15]:
a

array([[ 0.73885933, -0.36186927, -0.97568371, -0.59882436,  1.17143498],
       [-1.39220254, -0.47443503, -0.01327467,  0.87808177,  1.17166381],
       [-1.93295533,  0.53482944, -0.76302203, -1.7042804 , -0.56346165],
       [-1.76807265,  0.84463947,  0.34159376,  0.33046934, -1.80476383],
       [-0.70192645, -1.99594219, -0.02657045,  0.5563446 , -0.1923813 ]])

In [17]:
mat=a.T.dot(a)
mat

array([[ 9.83923897, -0.73304158,  0.18716344,  0.65457647,  3.64946963],
       [-0.73304158,  5.33928154,  0.29283792, -1.94270016, -2.42153335],
       [ 0.18716344,  0.29283792,  1.65172984,  1.97111436, -1.33995423],
       [ 0.65457647, -1.94270016,  1.97111436,  4.45291917,  0.58418007],
       [ 3.64946963, -2.42153335, -1.33995423,  0.58418007,  6.35672806]])

In [35]:
from numpy.linalg import inv, qr

In [36]:
inv(mat)

array([[ 0.16989452,  0.0316903 , -0.41829543,  0.19919402, -0.19194587],
       [ 0.0316903 ,  0.36651303, -0.66040064,  0.45539624, -0.05963277],
       [-0.41829543, -0.66040064,  4.65638611, -2.44454912,  1.19476173],
       [ 0.19919402,  0.45539624, -2.44454912,  1.55465379, -0.59904671],
       [-0.19194587, -0.05963277,  1.19476173, -0.59904671,  0.55169499]])

In [37]:
mat.dot(inv(a))

array([[ 0.73885933, -1.39220254, -1.93295533, -1.76807265, -0.70192645],
       [-0.36186927, -0.47443503,  0.53482944,  0.84463947, -1.99594219],
       [-0.97568371, -0.01327467, -0.76302203,  0.34159376, -0.02657045],
       [-0.59882436,  0.87808177, -1.7042804 ,  0.33046934,  0.5563446 ],
       [ 1.17143498,  1.17166381, -0.56346165, -1.80476383, -0.1923813 ]])

In [38]:
q,r=qr(mat)
r

array([[-10.54182634,   2.00919989,   0.15783321,  -1.25976827,
         -5.78774233],
       [  0.        ,  -5.89339078,  -0.17110283,   3.02192923,
          3.54567277],
       [  0.        ,   0.        ,  -2.91128448,  -3.95691225,
          2.77725459],
       [  0.        ,   0.        ,   0.        ,  -1.37163211,
         -2.73405233],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.68501519]])

In [39]:
x=np.array([[1,2,4],[5,6,7]])
y=np.array([[2,2],[4,5],[3,4]])

In [40]:
print(f'x:{x}\n\ny:{y}')

x:[[1 2 4]
 [5 6 7]]

y:[[2 2]
 [4 5]
 [3 4]]


In [41]:
x.dot(y) #equivalent to np.dot(x,y)

array([[22, 28],
       [55, 68]])

In [42]:
np.dot(x,y)

array([[22, 28],
       [55, 68]])

A matrix product between a 2D array and a suitably sized 1D array results in a 1D array:


In [43]:
np.dot(x,np.ones(3))

array([ 7., 18.])

numpy.linalg has a standard set of matrix decompositions and things like inverse and
determinant. 

In [44]:
import numpy as np
 
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])


In [45]:
# Rank of a matrix
print("Rank of A:", np.linalg.matrix_rank(A))
 
# Trace of matrix A
print("\nTrace of A:", np.trace(A))


Rank of A: 3

Trace of A: 11


In [46]:
# Determinant of a matrix
print("\nDeterminant of A:", np.linalg.det(A))
 
# Inverse of matrix A
print("\nInverse of A:\n", np.linalg.inv(A))
 
print("\nMatrix A raised to power 3:\n",
           np.linalg.matrix_power(A, 3))


Determinant of A: -306.0

Inverse of A:
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]

Matrix A raised to power 3:
 [[336 162 228]
 [406 162 469]
 [698 702 905]]


Matrix eigenvalues Functions
numpy.linalg.eigh(a, UPLO=’L’) : This function is used to return the eigenvalues and eigenvectors of a complex 
Hermitian (conjugate symmetric) or a real symmetric matrix.Returns two objects, a 1-D array containing the eigenvalues of a, 
and a 2-D square array or matrix (depending on the input type) of the corresponding eigenvectors (in columns).

In [97]:
from numpy import linalg as li

In [107]:
a = np.array([[1, -2j], [2j, 5]])

In [114]:
c,d=li.eigh(a)

In [115]:
d

array([[-0.92387953-0.        j, -0.38268343+0.        j],
       [ 0.        +0.38268343j,  0.        -0.92387953j]])

In [116]:
c

array([0.17157288, 5.82842712])

numpy.linalg.eig(a) : This function is used to compute the eigenvalues and right eigenvectors of a square array.

In [119]:
a=np.diag([1,2,3])
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [124]:
e,f=li.eigh(a)

In [121]:
e

array([1., 2., 3.])

In [122]:
f

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

numpy.dot

In [126]:
a=np.array(2+3j)
b=np.array(3+5j)

In [127]:
c=np.dot(a,b)

In [128]:
c

(-9+19j)

In [129]:
c=np.vdot(a,b)

In [130]:
c

(21+1j)

solve linear equation

In [141]:
c=np.array([[1,3],[4,6]])
d=np.array([3,4])

In [149]:
a = np.array([[1, 2,6], [3, 4,5],[7,8,5]])
 
# Creating an array using array
# function
b = np.array([8, 18,5])
 
print(("Solution of linear equations:", 
      np.linalg.solve(a, b)))

('Solution of linear equations:', array([-113.5 ,  110.25,  -16.5 ]))
